config:
  use_colors: true
  send_anonymous_usage_stats: False

default:
    target: dev
    outputs:
      dev:
        type: sqlite
        threads: 1
        database: 'sqlite'
        schema: 'main'
        schemas_and_paths:
          main: 'data/{{cookiecutter.database_name}}.db'
        schema_directory: 'data'
        extensions:
          - "sqlite_libs/crypto"
          - "sqlite_libs/math"
          - "sqlite_libs/text"